shell:
    poetry shell
video-extract:
    poetry run python data_pipeline/ingestion/video_search.py
extract-statistics:
    poetry run python data_pipeline/ingestion/get_video_interactions.py
video-processing:
    poetry run python data_pipeline/processing/extract_video_attributes.py
silver-processing:
    poetry run python data_pipeline/processing/video_attributes_from_bronze_to_silver.py
gold-processing:
    poetry run python data_pipeline/processing/video_attributes_from_silver_to_gold.py
bronze-statistics:
    poetry run python data_pipeline/processing/video_statistics_from_landing_to_bronze.py
silver-statistics:
    poetry run python data_pipeline/processing/video_statistics_from_bronze_to_silver.py